<div id="login-box" class="dark-bg">
    <div class="col-md-4 no-spaces">
        <div class="header-section col-md-12" style="padding-top:27px;">
            <i class="fa fa-medkit"></i>
            Przychodnia PLUS
        </div>
        <div class="header-section wide-button darker-bg col-md-12" style="height:50px;">
            <h3 class="no-spaces uppercase" style="padding-top:13px;">
                Rejestracja
            </h3>
        </div>    
        <div class="col-md-12">
            <p class="">
                Jeżeli jeszcze nie masz konta w Przychodni PLUS, udaj się do recepcji i poproś o dane do logowania.
            </p>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="col-md-8 light-bg no-spaces" style="height:100%;">
        <div class="header-section lighter-bg light-border col-md-12" style="color:#3B3A3F;padding-top:27px;">
            Zaloguj się
        </div>
        <div class="col-md-12" style="padding-bottom: 100px;">
            <form role="form">
                <fieldset class="row" style="margin-top:20px;">
                    <div class="col-md-6">
                        <div class="form-group ">
                            <label for="pesel">Numer PESEL:</label>
                            <input type="text" id="pesel" class="form-control" placeholder="Wpisz PESEL">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group ">
                            <label for="password">Hasło:</label>
                            <input type="password" id="password" class="form-control" placeholder="Wpisz hasło">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Zaloguj</button>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>