<?= $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?= $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <style>
             body { padding-top: 60px; }
        </style>
    </head>
    <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">Przychodnia Plus</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
        <div class="container">
            <?= $this->content; ?>
        </div>
    </body>
    <?= $this->inlineScript(); ?>
</html>
