<?= $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Przychodnia Plus</title>
        <?=
                $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/css/font-awesome.min.css')
                //->appendStylesheet($this->basePath() . '/css/sb-admin.css')
                ->appendStylesheet($this->basePath() . '/css/fullcalendar.css')
                ->appendStylesheet($this->basePath() . '/css/styles.css')
                ->appendStylesheet($this->basePath() . '/css/style.css')
        ?>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Share:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Quattrocento|Quattrocento+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    </head>
    <body>
        <div id="wrapper" class="">
            <div id="navigation" class="no-spaces navigation">
                <!-- Sidebar -->
                <nav class="navbar navbar-inverse dark-bg" role="navigation">                        
                    <!--<a id="main-menu-toggle" class="hidden-phone open"><i class="fa fa-reorder"></i></a>-->

                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <!--                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                                    <span class="icon-bar"></span>
                                                    <span class="icon-bar"></span>
                                                    <span class="icon-bar"></span>
                                                </button>-->
                        <a class="navbar-brand" href="<?= $this->url('home', array('action' => 'index')); ?>">
                            <i class="fa fa-medkit"></i>
                            Przychodnia PLUS
                        </a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="">
                        <ul class="nav navbar-nav side-nav">
                            <li class="">
                                <a href="<?= $this->url('home', array('action' => 'index')); ?>">
                                    <i class="fa fa-dashboard"></i> 
                                    <span>Stan PLUS</spam>
                                </a>
                            </li>
                            <li>
                                <a href="<?= $this->url('home', array('action' => 'schedule')); ?>">
                                    <i class="fa fa-calendar"></i> 
                                    <span>Terminarz PLUS</spam>
                                </a>
                            </li>
                            <li>
                                <a href="<?= $this->url('home', array('action' => 'diagnosis')); ?>">
                                    <i class="fa fa-stethoscope"></i> 
                                    <span>Diagnoza PLUS</spam>
                                </a>
                            </li>
                            <li>
                                <a href="<?= $this->url('home', array('action' => 'patient')); ?>">
                                    <i class="fa fa-user"></i> 
                                    <span>Pacjent PLUS</spam>
                                </a>
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right navbar-user">
                            <li class="dropdown user-dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-user-md"></i> 
                                    Jan Kowalski 
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-power-off"></i> 
                                            Wyloguj
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </div>
            <div id="content">
                <div class="container fullscreen light-bg">
                    <div class="row">
                        <div id="sidebar-left" class="col-sm-1" style="min-height: 0px; display: block;">
                            <div class="nav-collapse sidebar-nav">            
                                <ul id="navigation" class="nav nav-tabs nav-stacked">
                                    <li class="active">
                                        <a href="#">
                                            <i class="fa fa-facebook"></i> 
                                            <span class="hidden-sm">
                                                Menu 1                
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="" href="#">
                                            <i class="fa fa-bookmark-o"></i>
                                            <span class="hidden-sm">
                                                Menu 2                
                                            </span>
                                        </a>

                                    </li>
                                    <li>
                                        <a class="" href="#">
                                            <i class="fa fa-umbrella"></i>
                                            <span class="hidden-sm"> 
                                                Menu 3                
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="" href="#">
                                            <i class="fa fa-book"></i>
                                            <span class="hidden-sm">
                                                Menu 4                
                                            </span>
                                        </a>

                                    </li>

                                </ul>
                            </div>
                        </div>
                        <div id="page-wrapper" class="col-sm-11">
                            <?= $this->content; ?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div><!-- /#page-wrapper -->
            </div>
            <div class="clearfix"></div>
        </div><!-- /#wrapper -->
    </body>    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <?= $this->inlineScript(); ?>
    <?php
    echo $this->headScript()
            ->appendFile($this->basePath() . '/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/fullcalendar.min.js')
            ->appendFile($this->basePath() . '/js/custom.js')
    ;
    ?>
</html>
