<div class="col-md-12">
    <h1>Diagnoza PLUS <small>Optymalizacja diagnozowania</small></h1>
</div>
<div class="row">
    <div class="col-md-12" style="margin-bottom:20px">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#consult">Konsultacje z lekarzem</button>
        <button type="button" class="btn btn-primary">Dodaj diagnozę</button>
        <button type="button" class="btn btn-primary">Archiwum badań</button>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-clock-o"></i> Historia diagnoz</h3>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <span class="badge">teraz</span>
                        <i class="fa fa-info"></i> Grypa
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">4 minut(y) temu</span>
                        <i class="fa fa-info"></i> Zapalenie płuc
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">23 minut(y) temu</span>
                        <i class="fa fa-info"></i> Grypa
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">42 minut(y) temu</span>
                        <i class="fa fa-info"></i> Grypa
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">55 minut(y) temu</span>
                        <i class="fa fa-info"></i> Grypa żołądkowa
                    </a>
                </div>
                <div class="text-right">
                    <a href="#">Zobacz pełną historię <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-comments"></i> Komentarze pacjentów</h3>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <span class="badge">teraz</span>
                        <i class="fa fa-comment"></i> Super!
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">4 minut(y) temu</span>
                        <i class="fa fa-comment"></i> 2/10
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">23 minut(y) temu</span>
                        <i class="fa fa-comment"></i> nie o taką Polskiem walczyłem
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">42 minut(y) temu</span>
                        <i class="fa fa-comment"></i> Świetnie!
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">55 minut(y) temu</span>
                        <i class="fa fa-comment"></i> Tu wpisz komentarz...
                    </a>
                </div>
                <div class="text-right">
                    <a href="#">Zobacz wszystkie komentarze <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="consult" tabindex="-1" role="dialog" aria-labelledby="label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="label">Konsultacje lekarskie</h4>
            </div>
            <div class="modal-body">
                <h3>Wybierz specjalistę:</h3>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">dr Lekarz Przypadkowy</h3>
                        <input type="checkbox" class="pull-right" style="margin-top:-16px;"/>
                    </div>
                    <div class="panel-body">
                        Specjalista - Onkolog
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">dr Władysław Raczek</h3>
                        <input type="checkbox" class="pull-right" style="margin-top:-16px;"/>
                    </div>
                    <div class="panel-body">
                        Specjalista - Ginekolog
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">dr Marzena Maksoń</h3>
                        <input type="checkbox" class="pull-right" style="margin-top:-16px;"/>
                    </div>
                    <div class="panel-body">
                        Specjalista - Pediatra
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                <button type="button" class="btn btn-primary">Połącz</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->