<div class="col-lg-12">
    <h1>Stan PLUS <small>Przegląd statystyk przychodni</small></h1>
</div>
<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-6">
                        <i class="fa fa-group fa-5x"></i>
                    </div>
                    <div class="col-xs-6 text-right">
                        <p class="announcement-heading">4</p>
                        <p class="announcement-text">Nowych pacjentów!</p>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer announcement-bottom">
                    <div class="row">
                        <div class="col-xs-6">
                            Zobacz listę
                        </div>
                        <div class="col-xs-6 text-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-6">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-6 text-right">
                        <p class="announcement-heading">12</p>
                        <p class="announcement-text">Przyjętych pacjentów</p>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer announcement-bottom">
                    <div class="row">
                        <div class="col-xs-6">
                            Zobacz listę
                        </div>
                        <div class="col-xs-6 text-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-success">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-6">
                        <i class="fa fa-stethoscope fa-5x"></i>
                    </div>
                    <div class="col-xs-6 text-right">
                        <p class="announcement-heading">18</p>
                        <p class="announcement-text">Wykonanych zabiegów</p>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer announcement-bottom">
                    <div class="row">
                        <div class="col-xs-6">
                            Zobacz listę
                        </div>
                        <div class="col-xs-6 text-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-6">
                        <i class="fa fa-medkit fa-5x"></i>
                    </div>
                    <div class="col-xs-6 text-right">
                        <p class="announcement-heading"><10</p>
                        <p class="announcement-text">Brak strzykawek!</p>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer announcement-bottom">
                    <div class="row">
                        <div class="col-xs-6">
                            Przejdź do zamówień
                        </div>
                        <div class="col-xs-6 text-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-clock-o"></i> Ostatnia aktywność</h3>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <span class="badge">teraz</span>
                        <i class="fa fa-calendar"></i> Zmiana terminarza (dr Wojciech Wadimowski)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">4 minut(y) temu</span>
                        <i class="fa fa-user"></i> Zarejestrowano pacjenta (Janusz Rubin)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">23 minut(y) temu</span>
                        <i class="fa fa-truck"></i> Zamówiono strzykawki (600 sztuk)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">42 minut(y) temu</span>
                        <i class="fa fa-user"></i> Zarejestrowano pacjenta (Jeremiasz Gwóźdź)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">55 minut(y) temu</span>
                        <i class="fa fa-user"></i> Zarejestrowano pacjenta (Anna Banik)
                    </a>
                </div>
                <div class="text-right">
                    <a href="#">Zobacz listę <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-group"></i> Kolejka pacjentów</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped tablesorter">
                        <thead>
                            <tr>
                                <th class="header headerSortDown">Lp. <i class="fa fa-sort"></i></th>
                                <th class="header">Imię i nazwisko <i class="fa fa-sort"></i></th>
                                <th class="header">Godzina rejestracji <i class="fa fa-sort"></i></th>
                                <th class="header">Przewidywany czas obsługi <i class="fa fa-sort"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>3319</td>
                                <td>Rafał Dzwon</td>
                                <td>14:10</td>
                                <td>5 minut(y)</td>
                            </tr>
                            <tr>
                                <td>3320</td>
                                <td>Arkadiusz Małolepszy</td>
                                <td>14:11</td>
                                <td>15 minut(y)</td>
                            </tr>
                            <tr>
                            <tr>
                                <td>3321</td>
                                <td>Anita Robotycka</td>
                                <td>14:15</td>
                                <td>15 minut(y)</td>
                            </tr>
                            <tr>
                                <td>3322</td>
                                <td>Michał Król</td>
                                <td>14:30</td>
                                <td>45 minut(y)</td>
                            </tr>
                            <tr>
                                <td>3323</td>
                                <td>Agnieszka Włodarska</td>
                                <td>14:45</td>
                                <td>30 minut(y)</td>
                            </tr>
                            <tr>
                                <td>3324</td>
                                <td>Adam Frankowski</td>
                                <td>14:48</td>
                                <td>32 minut(y)</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="text-right">
                    <a href="#">Zobacz wszystkich zarejestrowanych <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>