<div class="col-lg-12">
    <h1>Pacjent PLUS <small>Szczegóły pacjenta</small></h1>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="photo">
            <i class="fa fa-user"></i>
        </div>
    </div>
    <div class="col-md-4">
        <dl>
            <dd>Radosław</dd>
            <dt>Imię</dt>
            <dd>Janus</dd>
            <dt>Nazwisko</dt>
            <dd>06.11.1986r.</dd>
            <dt>Data urodzin</dt>
            <dd>Kraków</dd>
            <dt>Miejsce urodzenia</dt>
            <dd>06118656039</dd>
            <dt>PESEL</dt>
            <dd>TAK</dd>
            <dt>Ubezpieczenie</dt>
        </dl>
    </div>
    <div class="col-md-4">
        <dl>
            <dd>0 Rh-</dd>
            <dt>Grupa krwi</dt>
            <dd>dr Tadeusz Źrebie</dd>
            <dt>Doktor prowadzący</dt>
            <dd>-</dd>
            <dt>Choroby przewlekłe</dt>
            <dd>-</dd>
            <dt>Szczepienia</dt>
            <dd>Praca</dd>
            <dt>Uczulenia</dt>
        </dl>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-clock-o"></i> Historia aktywności</h3>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <span class="badge">teraz</span>
                        <i class="fa fa-calendar"></i> Zmiana terminarza (dr Wojciech Wadimowski)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">4 minut(y) temu</span>
                        <i class="fa fa-user"></i> Zarejestrowano pacjenta (Janusz Rubin)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">23 minut(y) temu</span>
                        <i class="fa fa-truck"></i> Zamówiono strzykawki (600 sztuk)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">42 minut(y) temu</span>
                        <i class="fa fa-user"></i> Zarejestrowano pacjenta (Jeremiasz Gwóźdź)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">55 minut(y) temu</span>
                        <i class="fa fa-user"></i> Zarejestrowano pacjenta (Anna Banik)
                    </a>
                </div>
                <div class="text-right">
                    <a href="#">Zobacz pełną historię <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-clock-o"></i> Historia leczenia</h3>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <span class="badge">teraz</span>
                        <i class="fa fa-calendar"></i> Zmiana terminarza (dr Wojciech Wadimowski)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">4 minut(y) temu</span>
                        <i class="fa fa-user"></i> Zarejestrowano pacjenta (Janusz Rubin)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">23 minut(y) temu</span>
                        <i class="fa fa-truck"></i> Zamówiono strzykawki (600 sztuk)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">42 minut(y) temu</span>
                        <i class="fa fa-user"></i> Zarejestrowano pacjenta (Jeremiasz Gwóźdź)
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">55 minut(y) temu</span>
                        <i class="fa fa-user"></i> Zarejestrowano pacjenta (Anna Banik)
                    </a>
                </div>
                <div class="text-right">
                    <a href="#">Zobacz pełną historię <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>