<div class="col-md-12">
    <h1>Terminarz PLUS <small>Zarządzanie personelem</small></h1>
</div>
<div class="col-md-12">
    <h3>Szukaj terminarza:</h3>
    <div class="form-group input-group">
        <input type="text" class="form-control">
        <span class="input-group-addon"><i class="fa fa-search"></i></span>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-calendar"></i> dr Lekarz Przypadkowy</h3>
        </div>
        <div class="panel-body">
            <div class="calendar"></div>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-calendar"></i> dr Władysław Raczek</h3>
        </div>
        <div class="panel-body">
            <div class="calendar"></div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="col-md-6">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-calendar"></i> dr Marzena Maksoń</h3>
        </div>
        <div class="panel-body">
            <div class="calendar"></div>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-calendar"></i> dr Tadeusz Zięba</h3>
        </div>
        <div class="panel-body">
            <div class="calendar"></div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="visits" tabindex="-1" role="dialog" aria-labelledby="label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="label">Kalendarz wizyt</h4>
            </div>
            <div class="modal-body">
                <div class="calendar-spec"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->